### ISSUE TITLE
Error while using the CLI to scan resteasy examples WAR.

### ISSUE THREAD

**Issue by liweinan** [wildfly/wildfly-glow#23]
While I'm trying to use the `wildfly-glow` cli to scan the built WAR from the RESTEasy example:

- https://github.com/resteasy/resteasy-examples/tree/main/tracing-example

with the following command:

```bash
weli@192:~/w/w/wildfly-glow-1.0.0.Alpha8
➤ ./wildfly-glow scan /Users/weli/.m2/repository/dev/resteasy/examples/tracing-example/6.0.1-SNAPSHOT/tracing-example-6.0.1-SNAPSHOT.war                      23:24:11
```

It generates the following error:

```bash
Wildfly Glow is scanning...
ERROR: Exception occured while retrieving known Galleon feature-packs for version null. Cause: Connection refused
```

Here are the details:

<img width="1237" alt="image" src="https://github.com/wildfly/wildfly-glow/assets/201907/7191e814-6759-4eac-ba38-34dd19baaae2">

**Comment by liweinan** [comment]
@jfdenise I'm not sure whether it's my usage problem or not, could you please help to check it when you have time? Thanks!

**Comment by liweinan** [comment]
The used example is here: https://github.com/resteasy/resteasy-examples/tree/main/tracing-example

**Comment by jfdenise** [comment]
@liweinan , it seems that you can't access https://raw.githubusercontent.com/wildfly/wildfly-galleon-feature-packs/release/versions.yaml

Can you try: wget https://raw.githubusercontent.com/wildfly/wildfly-galleon-feature-packs/release/versions.yaml

**Comment by liweinan** [comment]
@jfdenise Okay I see, let me try to configure proxy.

**Comment by liweinan** [comment]
After setting the proxy I can run the command:

```bash
➤ JAVA_OPTS="-Dhttp.proxyHost=localhost -Dhttp.proxyPort=8829 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8829" ./wildfly-glow scan /Users/weli/.m2/repository/dev/resteasy/examples/tracing-example/6.0.1-SNAPSHOT/tracing-example-6.0.1-SNAPSHOT.war
Wildfly Glow is scanning...
context: bare-metal
enabled profile: none
galleon discovery
- feature-packs
   org.wildfly:wildfly-galleon-pack:30.0.0.Final
- layers
   ee-core-profile-server
   jaxrs

Some suggestions have been found. You could enable suggestions with --suggest option.
To provision the WildFly server for your deployment add the --provision=SERVER option to the scan command
```

@jfdenise Thanks for teaching! :D
