### ISSUE TITLE
High Availability Option

### ISSUE THREAD

**Issue by fabrii** [wildfly/wildfly-glow#79]
When using "--ha" option, the produced standalone.xml does not change. I was expecting some additional subsystems as distributable-web or infinispan. Is this a bug or am I misunderstanding?

Thanks

**Comment by fabrii** [comment]
Adding <distributable /> to web.xml made it work

**Comment by fabrii** [comment]
Another related question:

Is --ha working together with --cloud ?

I read in some blogs, that for HA to work in Kubernetes/OpenShift, we need a discovery protocol called KUBE_PING, but I dont see references to this in the standalone.

**Comment by jfdenise** [comment]
Hi @fabrii , yes KUBE_PING will be automatically enabled when you deploy to the cloud. So --ha and --cloud are good together.
You can give it a try by using the --provision=openshift --ha (you need to be connected to an openshift cluster such as the sandbox: https://developers.redhat.com/developer-sandbox
The DNS_PING will be enabled in the deployment, a ping headless service will get started and, at startup time, the protocol will get added to the server configuration.
BTW, we are working at a kind of dry-run of the openshift provisioning to "just" generate the openshift resources and Docker files allowing you to do that in offline mode.

**Comment by fabrii** [comment]
Thank you!
