### ISSUE TITLE
jakarta.annotation.sql.DataSourceDefinition can bring datasource

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-glow#91]
Such definition present in source code would resolve some datasources referenced from persistence.xml.
One issue with DataSourceDefinition is that they don't define the driver in use.
For example:
```
@DataSourceDefinition(name="java:jboss/datasources/batch-processingDS",
        className="org.h2.jdbcx.JdbcDataSource",
        url="jdbc:h2:mem:batch-processing;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1",
        user="sa",
        password="sa"
)
```
The className and optionally the URL needs to be recognized (pattern) to understand that the h2 driver is required.

**Comment by jamezp** [comment]
Parsing the url seems a bit tricky TBH. I kind of think we should maybe have a default, h2, and potentially fail if the url doesn't start with `jdbc:h2` and require a defined database driver.
